/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

module reversible_cells_smoke(abc, result);
  input [2:0] abc;
  wire [2:0] abc;
  output [5:0] result;
  wire [5:0] result;
  wire VDD;
  wire VGND;
  rev_cnot u_cnot (
    .A(abc[2]),
    .A_OUT(result[4]),
    .B(abc[1]),
    .B_OUT(result[3]),
    .VDD(1'h1),
    .VGND(1'h0)
  );
  rev_not u_not (
    .A(abc[2]),
    .VDD(1'h1),
    .VGND(1'h0),
    .Y(result[5])
  );
  rev_toffoli u_toffoli (
    .A(abc[2]),
    .A_OUT(result[2]),
    .B(abc[1]),
    .B_OUT(result[1]),
    .C(abc[0]),
    .C_OUT(result[0]),
    .VDD(1'h1),
    .VGND(1'h0)
  );
  assign VGND = 1'h0;
  assign VDD = 1'h1;
endmodule
