#!/usr/bin/env python3
"""Generate/check the 4/8 MAC placement against a flattened Yosys JSON netlist.

Run after synthesis: python3 scripts/place_macros.py path/to/netlist.json
Use --check to verify an existing placement without changing it.
Coordinates are microns; this is macro floorplanning, not routing/signoff.
"""
import argparse
from collections import Counter
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT/'src/macro_placement.cfg'
# TTSKY26c SKY130 1x1 DIEAREA is 161 x 111.52 um. Stay within a smaller
# 160 x 100 envelope too. Leave top-of-tile rows for storage/control cells.
LEFT, RIGHT, BOTTOM = 4.60, 156.40, 5.44
X_GAP, Y_GAP = 1.38, 1.36


def macros(netlist):
    modules = json.loads(netlist.read_text())['modules']
    tops = [m for m in modules.values() if int(m.get('attributes', {}).get('top', '0'), 2)]
    assert len(tops) == 1, 'Expected one flattened top module'
    cells = {n: c['type'] for n, c in tops[0]['cells'].items() if c['type'].startswith('rev_')}
    assert Counter(cells.values()) == {'rev_cnot': 112, 'rev_toffoli': 76}, 'Unexpected MAC gate count'
    sizes = {}
    for kind in set(cells.values()):
        meta = json.loads((ROOT/f'src/reversible_stdcells/layout/views/{kind}/geometry.json').read_text())
        sizes[kind] = (meta['width_um'], meta['height_um'])
        assert abs(meta['height_um']-5.44) < 1e-6
    return cells, sizes


def validate(placements, cells, sizes):
    assert set(placements) == set(cells), 'Missing or unknown macro instances'
    boxes = {}
    for name, (x, y, orientation) in placements.items():
        assert orientation == 'N', 'This floorplan uses unrotated macros'
        w, h = sizes[cells[name]]
        assert LEFT-1e-6 <= x and x+w <= RIGHT+1e-6, name
        assert BOTTOM-1e-6 <= y and y+h <= 100, name
        boxes[name] = (x, y, x+w, y+h)
    for i, (name, a) in enumerate(boxes.items()):
        for other, b in list(boxes.items())[i+1:]:
            # Check explicit channels, stronger than merely no overlapping boxes.
            assert (a[2]+X_GAP <= b[0]+1e-6 or b[2]+X_GAP <= a[0]+1e-6 or
                    a[3]+Y_GAP <= b[1]+1e-6 or b[3]+Y_GAP <= a[1]+1e-6), (name, other)
    area = sum(sizes[k][0]*sizes[k][1] for k in cells.values())
    print(f'PASS: {len(boxes)} macros; area {area:.4f} um^2; '
          f'right {max(b[2] for b in boxes.values()):.3f}; top {max(b[3] for b in boxes.values()):.3f}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('netlist', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    cells, sizes = macros(args.netlist)
    placements = {}
    if args.check:
        for line in OUTPUT.read_text().splitlines():
            if not line.strip() or line.startswith('#'):
                continue
            name, x, y, orientation = line.split()
            assert name not in placements, f'Duplicate: {name}'
            placements[name] = (float(x), float(y), orientation)
    else:
        # Natural hierarchy order keeps partial-product rows and each ripple
        # stage together. Alternate row direction to avoid long return wires.
        names = sorted(cells, key=lambda n: [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', n)])
        rows, row, used = [], [], 0.0
        for name in names:
            w, _ = sizes[cells[name]]
            if row and used+w > RIGHT-LEFT+1e-6:
                rows.append(row)
                row, used = [], 0.0
            row.append(name)
            used += w+X_GAP
        rows.append(row)
        for r, row in enumerate(rows):
            x = LEFT
            for name in row if r % 2 == 0 else reversed(row):
                placements[name] = (round(x, 3), round(BOTTOM+r*(5.44+Y_GAP), 3), 'N')
                x += sizes[cells[name]][0]+X_GAP
    validate(placements, cells, sizes)
    if not args.check:
        OUTPUT.write_text('# Generated by scripts/place_macros.py; names match flattened synthesis.\n'
                          '# instance x_um y_um orientation; no escaping of brackets or dots.\n'+
                          ''.join(f'{n} {x:.3f} {y:.3f} {o}\n' for n,(x,y,o) in placements.items()))


if __name__ == '__main__':
    main()
